/// Flutter icons WaterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WaterIcons
///      fonts:
///       - asset: fonts/WaterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WaterIcons {
  WaterIcons._();

  static const _kFontFam = 'WaterIcons';
  static const String? _kFontPkg = null;

  static const IconData glassofwater_84019 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_glass = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
